version: "3.8"

services:
  db:
    container_name: $COMPOSE_PROJECT_NAME-database
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network

  wordpress:
    container_name: $COMPOSE_PROJECT_NAME-wordpress
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WP_VERSION: $WP_VERSION
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DEV: false
      WORDPRESS_CONFIG_EXTRA: |
        $WP_CONFIG_EXTRA
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - $WP_HTDOCS:/var/www/html
      - $WP_THEME_FOLDER:/var/www/html/wp-content/themes
      - $WP_UPLOAD_FOLDER:/var/www/html/wp-content/uploads
      - $WP_PLUGINS_FOLDER:/var/www/html/wp-content/plugins
      - ./conf/ssl:/etc/ssl/private/
      - ./conf/ssl/ssl-cert-snakeoil.key:/etc/ssl/certs/ssl-cert-snakeoil.key
      - ./conf/ssl/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - $WEBSERVER_HTTP_PORT:80
      - $WEBSERVER_HTTPS_PORT:443
    networks:
      - app-network

  wordpress-frontend:
    container_name: $COMPOSE_PROJECT_NAME-frontend
    build:
      context: $WP_FRONTEND
      dockerfile: Dockerfile
    command: yarn dev --host
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PUPPETEER_SKIP_DOWNLOAD: false
    volumes:
      - $WP_FRONTEND:/app
      - wp_node_modules:/app/node_modules
    ports:
      - $FRONTEND_HTTP_PORT:5173

  myphpadmin:
    container_name: $COMPOSE_PROJECT_NAME-myphpadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
    ports:
      - $PHPMYADMIN_PORT:80
    networks:
      - app-network

volumes:
  dbdata:
  wp_node_modules:

networks:
  app-network:
    driver: bridge
